name: Push Workflow

on:
  push:
    branches:
      - main
      - develop

jobs:
  lint-and-test:
    name: Lint and Test Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-interaction

      - name: Run Linter
        run: |
          ./vendor/bin/php-cs-fixer fix --dry-run --diff

      - name: Run Tests
        run: |
          php artisan test

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: lint-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-interaction

      - name: Cache Config and Routes
        run: |
          php artisan config:cache
          php artisan route:cache

  security-check:
    name: Security Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Security Scan
        run: |
          trivy fs .

